export const GET_WEATHER = 'GET_WEATHER'
export const GET_ALL_WEATHER = 'GET_ALL_WEATHER'
export const SET_WEATHER = 'SET_WEATHER'
export const GET_CITIES = 'GET_CITIES'
export const SET_CITY = 'SET_CITY'
